export const runtime = "nodejs";

import { NextResponse } from "next/server";
import { pool } from "@/lib/db";
import { getAuthPayload } from "@/app/api/auth/me/route";
import { sendReferralEmail } from "@/lib/mailer";

// POST /api/teacher/students/[id]/assign
// Assigns an assessment type, creates a referral row, sends email.

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const auth = await getAuthPayload(req);
  if (!auth || auth.role !== "teacher") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { id } = await params;
  await req.json().catch(() => ({})); // body no longer required

  // The teacher does NOT choose a disability. Every referral is for the same
  // standard assessment; the child's condition is determined from the report.
  const assessmentType = "general";

  // Verify student belongs to this teacher
  const studentResult = await pool.query(
    "SELECT id, name, email FROM students WHERE id = $1 AND teacher_id = $2",
    [id, auth.userId]
  );
  if ((studentResult.rowCount ?? 0) === 0) {
    return NextResponse.json({ error: "Student not found" }, { status: 404 });
  }
  const student = studentResult.rows[0];

  // Get teacher name
  const teacherResult = await pool.query(
    "SELECT name FROM users WHERE id = $1",
    [auth.userId]
  );
  const teacherName = teacherResult.rows[0]?.name ?? "Your Teacher";

  // Update student's assessment type + status
  await pool.query(
    `UPDATE students
     SET referral_assessment_type = $1, assessment_status = 'not_started'
     WHERE id = $2`,
    [assessmentType, id]
  );

  // Create referral record (code generated by DB default)
  const referralResult = await pool.query(
    `INSERT INTO referrals (student_id, teacher_id, assessment_type)
     VALUES ($1, $2, $3)
     RETURNING id, code, expires_at`,
    [id, auth.userId, assessmentType]
  );
  const referral = referralResult.rows[0];

  // Build the referral link
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";
  const referralLink = `${baseUrl}/referral/${referral.code}`;

  // Send email (fire-and-forget, don't block response if SMTP not configured)
  try {
    await sendReferralEmail({
      to: student.email,
      studentName: student.name,
      teacherName,
      assessmentType,
      referralLink,
    });
  } catch (emailErr) {
    console.warn("Email send failed (SMTP not configured?):", emailErr);
    // Return success with a warning so teacher still gets the link
    return NextResponse.json({
      success: true,
      referralLink,
      referralCode: referral.code,
      expiresAt: referral.expires_at,
      emailSent: false,
      emailWarning: "Email could not be sent. Share the referral link manually.",
    });
  }

  return NextResponse.json({
    success: true,
    referralLink,
    referralCode: referral.code,
    expiresAt: referral.expires_at,
    emailSent: true,
  });
}
